name: Testes automatizados

on: 
  pull_request:
    branches: main
  push:
    branches: main


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with: 
          node-version: 14.x
     
      - name: Instalar dependencias
        run: yarn install
        
      - name: Rodar testes
        run: yarn test
      
      - name: Notificar falha no teste
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            You shall not pass
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
        


